- name: Install dependencies
  ansible.builtin.apt:
    name:
      #- tomcat9
      - maven
      - openjdk-21-jdk
    update_cache: yes
  become: yes



# Tomcat and the migration tool are downloaded from Tomcat's archive, and the latest version may not be available there.
# Alternatively, for the latest versions you can change the download url's to the ones found here:
# https://tomcat.apache.org/download-11.cgi   and   https://tomcat.apache.org/download-migration.cgi
- name: Download Tomcat 11
  get_url:
    url: "https://archive.apache.org/dist/tomcat/tomcat-11/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"
    dest: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"
- name: Extract Tomcat
  unarchive:
    src: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"
    dest: "."
    remote_src: yes
- name: Remove Tomcat tar.gz
  file:
    path: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"
    state: absent



- name: Download migration tool
  get_url:
    url: "https://archive.apache.org/dist/tomcat/jakartaee-migration/v{{ migration_version }}/binaries/jakartaee-migration-{{ migration_version }}-bin.tar.gz"
    dest: "/tmp/jakartaee-migration-{{ migration_version }}-bin.tar.gz"

- name: Extract migration tool
  unarchive:
    src: "/tmp/jakartaee-migration-{{ migration_version }}-bin.tar.gz"
    dest: "."
    remote_src: yes

- name: Remove migration tool tar.gz
  file:
    path: "/tmp/jakartaee-migration-{{ migration_version }}-bin.tar.gz"
    state: absent



- name: Clone Kielipankki-fcs-korp-endpoint
  ansible.builtin.git:
    repo: "https://github.com/CSCfi/Kielipankki-fcs-korp-endpoint.git"
    dest: "{{ fcs_directory }}"
    clone: yes

- name: Build package
  ansible.builtin.shell: "mvn clean package -D maven.test.skip=true"
  args:
    chdir: "{{ fcs_directory }}"

- name: Migrate WAR file
  ansible.builtin.shell: |
    ../jakartaee-migration-{{ migration_version }}/bin/migrate.sh \
    target/fcs-korp-endpoint-0.1-kp-SNAPSHOT.war \
    target/fcs-korp-endpoint-0.1-kp-SNAPSHOT-MIGRATED.war
  args:
    chdir: "{{ fcs_directory }}"

- name: Copy WAR to Tomcat webapps
  ansible.builtin.copy:
    src: "{{ fcs_directory }}/target/fcs-korp-endpoint-0.1-kp-SNAPSHOT-MIGRATED.war"
    dest: "apache-tomcat-{{ tomcat_version }}/webapps/fcs-korp.war" # not /var/lib ?
    remote_src: yes
  become: yes

- name: Start Tomcat
  ansible.builtin.shell: "./apache-tomcat-{{ tomcat_version }}/bin/startup.sh"