- name: Install dependencies
  ansible.builtin.apt:
    name:
      - openjdk-21-jdk
      - maven
      - tomcat10
      - tomcat-jakartaee-migration
    update_cache: yes
  become: yes

- name: Clone Kielipankki-fcs-korp-endpoint
  ansible.builtin.git:
    repo: "https://github.com/CSCfi/Kielipankki-fcs-korp-endpoint.git"
    dest: "{{ fcs_directory }}"
    clone: yes

- name: Build package
  ansible.builtin.shell: "mvn clean package -D maven.test.skip=true"
  args:
    chdir: "{{ fcs_directory }}"

- name: Migrate WAR file
  ansible.builtin.shell: |
    /usr/bin/javax2jakarta \
      target/fcs-korp-endpoint-0.1-kp-SNAPSHOT.war \
      target/fcs-korp-endpoint-0.1-kp-SNAPSHOT-MIGRATED.war
  args:
    chdir: "{{ fcs_directory }}"

- name: Copy WAR to Tomcat webapps
  ansible.builtin.copy:
    src: "{{ fcs_directory }}/target/fcs-korp-endpoint-0.1-kp-SNAPSHOT-MIGRATED.war"
    dest: "/var/lib/tomcat10/webapps/fcs-korp.war"
    remote_src: yes
  become: yes
  
