- name: Create virtual machine on cPouta
  hosts: localhost

  roles:
    - role: kielipankki.common.create_instances
      tags: create_instances

  vars:
    security_group_rules:
      - name: http 8080
        protocol: tcp
        port: 8080
        allowed_ips:
          - "128.214.255.214/32" #Kielipankki-proxy-pre-prod
          - "195.148.30.210/32" #Kielipankki-proxy-prod

- name: Setup FCS Korp endpoint
  hosts: fcs-korp-vm
  roles:
    - fcs-setup
    - firewall
